import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import node from '@astrojs/node';
import { readFileSync } from 'node:fs';

export default defineConfig({
  output: 'hybrid',
  adapter: node({ mode: 'standalone' }),
  vite: {
    resolve: {
      alias: {
        '@': '/src'
      }
    }
  },
  site: 'https://thebestaitoolsreview.com',
  trailingSlash: 'always',
  build: { format: 'directory' },
  redirects: {
    '/deep-dive-chatgpt/': '/blog/chatgpt-tutorial-guide-2026/',
    '/deep-dive-cursor/': '/blog/cursor-tutorial-guide-2026/',
    '/en/': '/',
    '/submit-prompt/': '/submit-tool/',
    '/blog/best-ai-tools-for-designers-2026/': '/blog/best-ai-tools-designers/',
    '/blog/free-ai-image-generator-2026/': '/blog/best-ai-image-generators/',
    '/blog/free-ai-logo-maker-2026/': '/best/designers/',
    '/blog/free-ai-voice-generator-2026/': '/best/audio/',
    '/best/design/': '/best/designers/',
    '/best/ecommerce/': '/best/small-business/',
    '/best/marketing/': '/best/content-writing/',
    '/best/social-media/': '/best/content-writing/',
    '/best/translation/': '/best/text/',
    '/zh/best/ai-for-teachers/': '/zh/solutions/ai-for-education/',
    '/zh/best/students/': '/zh/solutions/ai-for-students/',
    '/templates/comfyui-img2img/': '/templates/comfyui-txt2img/',
    '/zh/author/sofia-reyes/': '/author/sofia-reyes/',
    '/zh/templates/meeting-minutes/': '/templates/meeting-minutes/',
    '/zh/templates/nda-template/': '/templates/nda-template/',
    '/zh/templates/prd-template/': '/templates/prd-template/',
    '/zh/templates/qbr-template/': '/templates/qbr-template/',
    '/zh/templates/resume-pm/': '/templates/resume-pm/',
    '/zh/templates/srs-template/': '/templates/srs-template/',
    '/zh/templates/swot-template/': '/templates/swot-template/',
    '/zh/templates/ui-prompt-template/': '/templates/ui-prompt-template/',
    '/zh/workflows/comfyui-style-transfer-pipeline/': '/workflows/comfyui-style-transfer-pipeline/',
    '/zh/workflows/comfyui-video-frame-interpolation/': '/workflows/comfyui-video-frame-interpolation/',
    '/zh/workflows/dify-sales-assistant/': '/workflows/dify-sales-assistant/',

    '/vs/bloop-ai-vs-cursor/': '/vs/',
    '/vs/descript-vs-runway/': '/vs/',
    '/vs/stable-diffusion-vs-ideogram/': '/vs/',
    '/zh/vs/consensus-pro-vs-paperpile/': '/zh/vs/',
    '/zh/vs/naturalreader-vs-speechify/': '/zh/vs/',
    '/zh/vs/notion-ai-vs-coda-ai/': '/zh/vs/',
    '/zh/vs/sweep-ai-vs-cursor/': '/zh/vs/',
    '/prompts/any-brand-guidelines/': '/prompts/',
    '/prompts/any-docker/': '/prompts/',
    '/prompts/any-llm-eval/': '/prompts/',
    '/prompts/any-marketing-funnel/': '/prompts/',
    '/prompts/any-ml-pipeline/': '/prompts/',
    '/prompts/any-rag-chunk/': '/prompts/',
    '/prompts/any-react-spec/': '/prompts/',
    '/prompts/any-thumbnail/': '/prompts/',
    '/prompts/any-tiktok-script/': '/prompts/',
    '/prompts/chatgpt-event/': '/prompts/',
    '/prompts/chatgpt-garden/': '/prompts/',
    '/prompts/chatgpt-habits/': '/prompts/',
    '/prompts/chatgpt-meeting-agenda/': '/prompts/',
    '/prompts/chatgpt-wardrobe/': '/prompts/',
    '/prompts/claude-adr/': '/prompts/',
    '/prompts/cursor-api-endpoint/': '/prompts/',
    '/prompts/mj-floral-pattern/': '/prompts/',
    '/alternatives/adobe-podcast/': '/tools/adobe-podcast/',
    '/alternatives/anyword-ai/': '/tools/anyword-ai/',
    '/alternatives/audioalter/': '/tools/audioalter/',
    '/alternatives/bhuman/': '/tools/bhuman/',
    '/alternatives/clockwise-ai/': '/tools/clockwise-ai/',
    '/alternatives/easy-ai/': '/tools/easy-ai/',
    '/alternatives/glide-ai/': '/tools/glide-ai/',
    '/alternatives/harpa-ai/': '/tools/harpa-ai/',
    '/alternatives/ink-ai/': '/tools/ink-ai/',
    '/alternatives/listnr/': '/tools/listnr/',
    '/alternatives/lm-studio/': '/tools/lm-studio/',
    '/alternatives/magickpen/': '/tools/magickpen/',
    '/alternatives/maxai/': '/tools/maxai/',
    '/alternatives/motion-ai/': '/tools/motion-ai/',
    '/alternatives/munch-ai/': '/tools/munch-ai/',
    '/alternatives/mutable-ai/': '/tools/mutable-ai/',
    '/alternatives/nightcafe/': '/tools/nightcafe/',
    '/alternatives/novita-ai/': '/tools/novita-ai/',
    '/alternatives/pika-labs/': '/tools/pika-labs/',
    '/alternatives/playground-ai/': '/tools/playground-ai/',
    '/alternatives/reflect-notes/': '/tools/reflect-notes/',
    '/alternatives/rytr-ai/': '/tools/rytr-ai/',
    '/alternatives/seaart/': '/tools/seaart/',
    '/alternatives/songdonkey/': '/tools/songdonkey/',
    '/alternatives/sudowrite-ai/': '/tools/sudowrite-ai/',
    '/alternatives/textcortex/': '/tools/textcortex/',
    '/alternatives/ttsmaker/': '/tools/ttsmaker/',
    '/alternatives/twilio-ai/': '/tools/twilio-ai/',
    '/alternatives/vizcom-ai/': '/tools/vizcom-ai/',
    '/alternatives/voice123/': '/tools/voice123/',
    '/alternatives/voicemod-pro/': '/tools/voicemod-pro/',
    '/zh/workflows/dify-content-pipeline/': '/zh/workflows/',
    '/zh/workflows/dify-rag-document-qna/': '/zh/workflows/',
    '/zh/workflows/mcp-github-code-review/': '/zh/workflows/',
    '/zh/workflows/n8n-api-monitor/': '/zh/workflows/',
    '/zh/workflows/n8n-marketing-automation/': '/zh/workflows/',
    '/zh/workflows/n8n-social-media-scheduler/': '/zh/workflows/',
    '/zh/zh/solutions/': '/zh/solutions/',
    '/zh/zh/solutions/ai-for-architecture/': '/zh/solutions/ai-for-architecture/',
    '/zh/zh/solutions/ai-for-bim/': '/zh/solutions/ai-for-bim/',
    '/zh/zh/solutions/ai-for-business/': '/zh/solutions/ai-for-business/',
    '/zh/zh/solutions/ai-for-civil-engineers/': '/zh/solutions/ai-for-civil-engineers/',
    '/zh/zh/solutions/ai-for-construction/': '/zh/solutions/ai-for-construction/',
    '/zh/zh/solutions/ai-for-creatives/': '/zh/solutions/ai-for-creatives/',
    '/zh/zh/solutions/ai-for-education/': '/zh/solutions/ai-for-education/',
    '/zh/zh/solutions/ai-for-finance/': '/zh/solutions/ai-for-finance/',
    '/zh/zh/solutions/ai-for-healthcare/': '/zh/solutions/ai-for-healthcare/',
    '/zh/zh/solutions/ai-for-hvac-engineers/': '/zh/solutions/ai-for-hvac-engineers/',
    '/zh/zh/solutions/ai-for-industrial-design/': '/zh/solutions/ai-for-industrial-design/',
    '/zh/zh/solutions/ai-for-legal/': '/zh/solutions/ai-for-legal/',
    '/zh/zh/solutions/ai-for-marketing/': '/zh/solutions/ai-for-marketing/',
    '/zh/zh/solutions/ai-for-mep-engineers/': '/zh/solutions/ai-for-mep-engineers/',
    '/zh/zh/solutions/ai-for-structural-engineers/': '/zh/solutions/ai-for-structural-engineers/',
    '/zh/zh/best/ai-agents/': '/zh/best/ai-agents/',
    '/zh/zh/workflows/dify-sales-assistant/': '/zh/workflows/dify-sales-assistant/',
    '/zh/zh/workflows/langgraph-customer-support/': '/zh/workflows/langgraph-customer-support/',
    '/zh/zh/workflows/mcp-claude-file-system/': '/zh/workflows/mcp-claude-file-system/',
    '/zh/zh/workflows/n8n-email-triage-agent/': '/zh/workflows/n8n-email-triage-agent/',
    '/zh/zh/workflows/comfyui-design-pipeline/': '/zh/workflows/',
    '/zh/zh/workflows/dify-content-pipeline/': '/zh/workflows/',
    '/zh/zh/workflows/dify-customer-support-bot/': '/zh/workflows/',
    '/zh/zh/workflows/dify-rag-document-qna/': '/zh/workflows/',
    '/zh/zh/workflows/mcp-github-code-review/': '/zh/workflows/',
    '/zh/zh/workflows/n8n-api-monitor/': '/zh/workflows/',
    '/zh/zh/workflows/n8n-lead-enrichment/': '/zh/workflows/',
    '/zh/zh/workflows/n8n-marketing-automation/': '/zh/workflows/',
    '/zh/zh/workflows/n8n-social-media-scheduler/': '/zh/workflows/',
    '/zh/zh/workflows/n8n-webhook-automation/': '/zh/workflows/',
    '/tool/[...slug]': '/tools/[...slug]',
    '/zh/tool/[...slug]': '/zh/tools/[...slug]',
    // SEO V2 P1-11：deep-dive-claude 软重定向页 → 明确 301 到深度评测正文
    '/deep-dive-claude/': '/blog/claude-vs-gemini-vs-chatgpt-2026/',
    '/zh/deep-dive-claude/': '/zh/blog/claude-vs-gemini-vs-chatgpt-2026/',
    // prompts 无数据 slug 移除后 → 301 到 prompts 列表
    '/prompts/any-cicd/': '/prompts/',
    '/prompts/any-etl-spec2/': '/prompts/',
    '/prompts/any-kb-structure/': '/prompts/',
    '/prompts/any-react-pat/': '/prompts/',
    '/prompts/chatgpt-biz-plan/': '/prompts/',
    '/prompts/cursor-worker/': '/prompts/',
    '/prompts/mj-landscape/': '/prompts/',
    '/zh/prompts/any-cicd/': '/zh/prompts/',
    '/zh/prompts/any-etl-spec2/': '/zh/prompts/',
    '/zh/prompts/any-kb-structure/': '/zh/prompts/',
    '/zh/prompts/any-react-pat/': '/zh/prompts/',
    '/zh/prompts/chatgpt-biz-plan/': '/zh/prompts/',
    '/zh/prompts/cursor-worker/': '/zh/prompts/',
    '/zh/prompts/mj-landscape/': '/zh/prompts/',
    // 批2-A：elevenlabs blog 重命名后，旧 slug 301 到新文件页（保住 GSC 收录流量）
    '/blog/how-to-use-elevenlabs-for-podcasts-2026/': '/blog/elevenlabs-tutorial-guide-2026/',
    '/zh/blog/how-to-use-elevenlabs-for-podcasts-2026/': '/zh/blog/elevenlabs-tutorial-guide-2026/',
  },
  i18n: { defaultLocale: 'en', locales: ['en', 'zh'], routing: { prefixDefaultLocale: false, fallbackType: 'rewrite' }, fallback: { zh: 'en' } },
  integrations: [
    sitemap({
      customPages: [
        // Explicitly include the zh home page (i18n fallback rewrites /zh/ to "/", so it is missed by auto-discovery)
        'https://thebestaitoolsreview.com/zh/',
        // zh templates/workflows pages served via i18n fallback rewrite (no zh source files) - not auto-discovered
        'https://thebestaitoolsreview.com/zh/templates/',
        'https://thebestaitoolsreview.com/zh/templates/meeting-minutes/',
        'https://thebestaitoolsreview.com/zh/templates/nda-template/',
        'https://thebestaitoolsreview.com/zh/templates/prd-template/',
        'https://thebestaitoolsreview.com/zh/templates/qbr-template/',
        'https://thebestaitoolsreview.com/zh/templates/resume-pm/',
        'https://thebestaitoolsreview.com/zh/templates/srs-template/',
        'https://thebestaitoolsreview.com/zh/templates/swot-template/',
        'https://thebestaitoolsreview.com/zh/templates/ui-prompt-template/',
        'https://thebestaitoolsreview.com/zh/workflows/claude-code-review-pipeline/',
        'https://thebestaitoolsreview.com/zh/workflows/comfyui-style-transfer-pipeline/',
        'https://thebestaitoolsreview.com/zh/workflows/comfyui-video-frame-interpolation/',
        'https://thebestaitoolsreview.com/zh/workflows/dify-data-analysis-agent/',
        'https://thebestaitoolsreview.com/zh/workflows/dify-sales-assistant/',
      ],
      // Exclude utility pages, soft-redirect pages and the home anchor link from the sitemap
      filter: (page) => {
        const path = page.replace(/^https?:\/\/[^/]+/, '');
        const softRedirects = [
          '/deep-dive-claude/',
          '/prompts/any-cicd/', '/prompts/any-etl-spec2/', '/prompts/any-kb-structure/',
          '/prompts/any-react-pat/', '/prompts/chatgpt-biz-plan/', '/prompts/cursor-worker/',
          '/prompts/mj-landscape/',
        ];
        // SEO V4: exclude all zh pages from sitemap to concentrate crawl budget on English content
        // noindexLowQuality: read from content-queue/noindex-pages.json (low-quality AIGC pages kept noindex)
        const noindexLowQuality = JSON.parse(
          readFileSync(new URL('./content-queue/noindex-pages.json', import.meta.url), 'utf-8')
        );
        return !path.startsWith('/zh/') &&
          !noindexLowQuality.includes(path) &&
          !path.includes('/ads.txt') &&
          !path.includes('/baidu_verify') &&
          !path.includes('/google') &&
          !path.includes('/robots.txt') &&
          !softRedirects.some(p => path === p || path.startsWith('/zh' + p));
      },
      changefreq: 'weekly',
      priority: 0.7,
      lastmod: new Date(),
    }),
  ],
});
