// ============================================================
// SEO V2 Phase 2 — 页面级 SEO 配置（S/A/B/C 级 50 页）
// 来源：《TheBestAIToolsReview SEO V2 行动计划》第 3 章
// 站点：https://thebestaitoolsreview.com
// 说明：status=exists 表示页面已存在于项目；status=missing
// 表示目标页尚未创建（后续 Phase 内容改造时补建）。
// 字段仅供集中管理使用，模板层渲染逻辑仍以页面源码为准。
// ============================================================

export type PageLevel = "S" | "A" | "B" | "C";
export type PageStatus = "exists" | "missing";

export interface SeoPage {
  id: string;                 // 任务书编号，如 S01
  level: PageLevel;
  slug: string;               // 路由 slug（不含语言前缀）
  path: string;               // 完整路径（en，带尾斜杠）
  type:
    | "blog"
    | "tool"
    | "solutions"
    | "best"
    | "templates"
    | "workflows"
    | "alternatives"
    | "vs"
    | "prompts";
  primaryKeyword: string;
  secondaryKeywords: string[];
  title: string;
  description: string;
  h1: string;
  cluster: string;            // 主题集群（clusters.ts 的 id）
  canonical: string;          // 绝对 canonical（en）
  schemaType: string[];       // 建议注入的 schema 类型
  internalLinks: string[];    // 建议内链（en 路径）
  status: PageStatus;
}

const site = "https://thebestaitoolsreview.com";

export const seoPages: SeoPage[] = [
  // ================= S 级（Top10 页，CTR + 内容增强） =================
  {
    id: "S01",
    level: "S",
    slug: "agnes-ai-review-free-omni-modal-api-2026",
    path: "/blog/agnes-ai-review-free-omni-modal-api-2026/",
    type: "blog",
    primaryKeyword: "agnes ai review",
    secondaryKeywords: ["is agnes ai free", "agnes ai pricing", "agnes ai api"],
    title: "Agnes AI Review 2026: Features, Pricing & Is It Worth It?",
    description:
      "Hands-on Agnes AI review 2026: is it really free? Features, pricing, API, multimodal quality, vs ChatGPT & Claude, pros & cons, and who should use it.",
    h1: "Agnes AI Review 2026: Features, Pricing & Is It Worth It?",
    cluster: "ai-reviews",
    canonical: `${site}/blog/agnes-ai-review-free-omni-modal-api-2026/`,
    schemaType: ["Article", "FAQPage"],
    internalLinks: ["/tool/agnes-ai/", "/alternatives/agnes-ai/", "/blog/agnes-ai-tutorial-guide-2026/"],
    status: "exists",
  },
  {
    id: "S02",
    level: "S",
    slug: "best-ai-video-generators-2026",
    path: "/blog/best-ai-video-generators-2026/",
    type: "blog",
    primaryKeyword: "best ai video generators",
    secondaryKeywords: ["ai video generator", "text to video ai", "ai video tools 2026"],
    title: "15 Best AI Video Generators in 2026: Tested & Compared",
    description:
      "We tested 15 best AI video generators in 2026: comparison table, pricing, text/image/video-to-video, resolution, duration, watermark & commercial usage.",
    h1: "15 Best AI Video Generators in 2026: Tested & Compared",
    cluster: "ai-video",
    canonical: `${site}/blog/best-ai-video-generators-2026/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/best/video/", "/blog/best-ai-image-generators-compared-2026/"],
    status: "exists",
  },
  {
    id: "S03",
    level: "S",
    slug: "best-ai-image-generators-compared-2026",
    path: "/blog/best-ai-image-generators-compared-2026/",
    type: "blog",
    primaryKeyword: "best ai image generators",
    secondaryKeywords: ["midjourney alternative", "stable diffusion vs midjourney", "krea ai"],
    title: "15 Best AI Image Generators in 2026: Tested & Compared",
    description:
      "The 15 best AI image generators compared: Midjourney, Stable Diffusion, Krea, Hotpot and more — real testing, pricing, features and FAQ.",
    h1: "15 Best AI Image Generators in 2026: Tested & Compared",
    cluster: "ai-image",
    canonical: `${site}/blog/best-ai-image-generators-compared-2026/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/best/image/", "/tool/midjourney/", "/tool/hotpot-ai/"],
    status: "exists",
  },
  {
    id: "S04",
    level: "S",
    slug: "lens-ai",
    path: "/tool/lens-ai/",
    type: "tool",
    primaryKeyword: "lens ai review",
    secondaryKeywords: ["lens ai", "lens ai app", "lens ai pricing"],
    title: "Lens AI Review 2026: Features, Pricing & Is It Worth It?",
    description:
      "Lens AI review 2026: features, pricing, free plan, how it works, use cases, pros & cons, alternatives, and who it's for.",
    h1: "Lens AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/lens-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/lens-ai/", "/best/image/"],
    status: "exists",
  },
  {
    id: "S05",
    level: "S",
    slug: "height-ai",
    path: "/tool/height-ai/",
    type: "tool",
    primaryKeyword: "height ai",
    secondaryKeywords: ["height ai project management", "height ai review", "height app"],
    title: "Height AI Review 2026: AI Project Management Features & Pricing",
    description:
      "Height AI review 2026: AI project management features, pricing, real-world testing, pros & cons, alternatives and FAQ.",
    h1: "Height AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/height-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/height-ai/", "/best/productivity/"],
    status: "exists",
  },
  {
    id: "S06",
    level: "S",
    slug: "shell-genie",
    path: "/tool/shell-genie/",
    type: "tool",
    primaryKeyword: "shellgenie",
    secondaryKeywords: ["shell genie", "shellgenie ai", "ai command line assistant"],
    title: "ShellGenie Review 2026: AI Command Line Assistant Explained",
    description:
      "ShellGenie review 2026: what it is, features, pricing, how the AI command line assistant works, pros & cons and alternatives.",
    h1: "ShellGenie Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/shell-genie/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/shell-genie/", "/best/code/"],
    status: "exists",
  },
  {
    id: "S07",
    level: "S",
    slug: "twipu-ai",
    path: "/tool/twipu-ai/",
    type: "tool",
    primaryKeyword: "twipu",
    secondaryKeywords: ["twipu ai", "twipu review", "twitter ai tool"],
    title: "Twipu Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Twipu review 2026: features, pricing, real-world testing, pros & cons, alternatives — keep existing CTR structure, extend FAQ & related tools.",
    h1: "Twipu Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/twipu-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/twipu-ai/", "/best/social-media/"],
    status: "exists",
  },
  {
    id: "S08",
    level: "S",
    slug: "how-to-use-claude-for-long-documents-2026",
    path: "/blog/how-to-use-claude-for-long-documents-2026/",
    type: "blog",
    primaryKeyword: "claude long documents",
    secondaryKeywords: ["how to use claude for long documents", "claude context window", "claude pdf"],
    title: "How to Use Claude for Long Documents in 2026 (Step-by-Step)",
    description:
      "Step-by-step guide to using Claude for long documents in 2026: context window tips, PDF handling, chunking strategies and real workflow tests.",
    h1: "How to Use Claude for Long Documents in 2026",
    cluster: "ai-tutorials",
    canonical: `${site}/blog/how-to-use-claude-for-long-documents-2026/`,
    schemaType: ["Article", "HowTo", "FAQPage"],
    internalLinks: ["/tool/claude/", "/blog/claude-vs-gemini-vs-chatgpt-2026/"],
    status: "exists",
  },
  {
    id: "S09",
    level: "S",
    slug: "bonsai-27b-on-device-ai-phone-2026",
    path: "/blog/bonsai-27b-on-device-ai-phone-2026/",
    type: "blog",
    primaryKeyword: "bonsai 27b",
    secondaryKeywords: ["bonsai 27b on device", "on device ai phone", "bonsai ai model"],
    title: "Bonsai 27B On-Device AI Phone 2026: Everything You Need to Know",
    description:
      "Bonsai 27B on-device AI phone explained: specs, on-device performance, privacy, pricing and whether it's worth it in 2026.",
    h1: "Bonsai 27B On-Device AI Phone 2026",
    cluster: "ai-hardware",
    canonical: `${site}/blog/bonsai-27b-on-device-ai-phone-2026/`,
    schemaType: ["Article", "FAQPage"],
    internalLinks: ["/blog/best-ai-tools-for-students-2026/"],
    status: "exists",
  },
  {
    id: "S10",
    level: "S",
    slug: "how-to-use-elevenlabs-for-podcasts-2026",
    path: "/blog/how-to-use-elevenlabs-for-podcasts-2026/",
    type: "blog",
    primaryKeyword: "elevenlabs podcast",
    secondaryKeywords: ["how to use elevenlabs for podcasts", "elevenlabs voice", "ai podcast voice"],
    title: "How to Use ElevenLabs for Podcasts in 2026 (Step-by-Step)",
    description:
      "Step-by-step: how to use ElevenLabs for podcasts in 2026 — voice cloning, TTS for narration, editing workflow, pricing and FAQ.",
    h1: "How to Use ElevenLabs for Podcasts in 2026",
    cluster: "ai-tutorials",
    canonical: `${site}/blog/how-to-use-elevenlabs-for-podcasts-2026/`,
    schemaType: ["Article", "HowTo", "FAQPage"],
    internalLinks: ["/tool/elevenlabs/", "/best/audio/"],
    status: "exists",
  },

  // ================= A 级（10~50 名，冲 Top10/Top20） =================
  {
    id: "A01",
    level: "A",
    slug: "ai-for-bim",
    path: "/solutions/ai-for-bim/",
    type: "solutions",
    primaryKeyword: "ai for bim",
    secondaryKeywords: ["ai for bim model checking", "bim quality assurance ai", "bim model inspection tool", "ai assistant for bim"],
    title: "AI for BIM in 2026: AI Tools for BIM Model Checking & QA",
    description:
      "AI for BIM in 2026: model checking, clash detection, model validation, drawing review, document analysis and the best AI tool stack for BIM teams.",
    h1: "AI for BIM in 2026: AI Tools for BIM Model Checking & QA",
    cluster: "ai-engineering",
    canonical: `${site}/solutions/ai-for-bim/`,
    schemaType: ["Article", "BreadcrumbList", "ItemList", "FAQPage"],
    internalLinks: [
      "/use-cases/bim-ai-tools/",
      "/solutions/ai-for-architecture/",
      "/solutions/ai-for-structural-engineers/",
      "/solutions/ai-for-electrical-engineers/",
    ],
    status: "exists",
  },
  {
    id: "A02",
    level: "A",
    slug: "ai-for-finance",
    path: "/solutions/ai-for-finance/",
    type: "solutions",
    primaryKeyword: "ai financial analysis",
    secondaryKeywords: ["ai for financial statements", "fp&a ai", "ai forecasting", "ai accounting tools"],
    title: "AI for Financial Analysis in 2026: Tools for Financial Statements & FP&A",
    description:
      "AI for financial analysis in 2026: tools for financial statements, FP&A, forecasting, budgeting, reporting, risk and accounting.",
    h1: "AI for Financial Analysis in 2026",
    cluster: "ai-finance",
    canonical: `${site}/solutions/ai-for-finance/`,
    schemaType: ["Article", "BreadcrumbList", "ItemList", "FAQPage"],
    internalLinks: ["/solutions/ai-for-bim/", "/best/productivity/"],
    status: "missing",
  },
  {
    id: "A03",
    level: "A",
    slug: "content-writing",
    path: "/best/content-writing/",
    type: "best",
    primaryKeyword: "best ai content writing tools",
    secondaryKeywords: ["ai content writer", "ai writing software", "content writing ai"],
    title: "Best AI Content Writing Tools in 2026: Tested & Compared",
    description:
      "The best AI content writing tools in 2026 compared: long-form writing, SEO, editing, pricing and real output tests.",
    h1: "Best AI Content Writing Tools in 2026",
    cluster: "ai-writing",
    canonical: `${site}/best/content-writing/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/best/text/", "/blog/best-ai-tools-for-content-writers-2026/"],
    status: "missing",
  },
  {
    id: "A04",
    level: "A",
    slug: "qbr-template",
    path: "/templates/qbr-template/",
    type: "templates",
    primaryKeyword: "qbr template",
    secondaryKeywords: ["quarterly business review template", "qbr deck template", "qbr meeting template"],
    title: "QBR Template 2026: Free Quarterly Business Review Template",
    description:
      "Free QBR template 2026: copy the quarterly business review deck structure, metrics to track, meeting agenda and tips.",
    h1: "QBR Template 2026",
    cluster: "business-templates",
    canonical: `${site}/templates/qbr-template/`,
    schemaType: ["Article", "HowTo"],
    internalLinks: ["/templates/pitch-deck/", "/best/productivity/"],
    status: "exists",
  },
  {
    id: "A05",
    level: "A",
    slug: "ai-for-architecture",
    path: "/solutions/ai-for-architecture/",
    type: "solutions",
    primaryKeyword: "ai for architecture",
    secondaryKeywords: ["ai architecture tools", "ai for architects", "ai concept design", "ai building design"],
    title: "AI for Architecture in 2026: Tools for Concept Design to Delivery",
    description:
      "AI for architecture in 2026: concept design, BIM, visualization, drawing review and code compliance — the full AI tool stack for architects.",
    h1: "AI for Architecture in 2026",
    cluster: "ai-engineering",
    canonical: `${site}/solutions/ai-for-architecture/`,
    schemaType: ["Article", "BreadcrumbList", "ItemList", "FAQPage"],
    internalLinks: ["/solutions/ai-for-bim/", "/best/ai-for-architects/", "/use-cases/architecture-ai-tools/"],
    status: "exists",
  },
  {
    id: "A06",
    level: "A",
    slug: "asana-ai",
    path: "/tool/asana-ai/",
    type: "tool",
    primaryKeyword: "asana ai",
    secondaryKeywords: ["asana ai review", "asana ai features", "asana intelligence"],
    title: "Asana AI Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Asana AI review 2026: Asana Intelligence features, pricing, real-world testing, pros & cons, alternatives and FAQ.",
    h1: "Asana AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/asana-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/asana-ai/", "/best/productivity/"],
    status: "exists",
  },
  {
    id: "A07",
    level: "A",
    slug: "connected-papers",
    path: "/tool/connected-papers/",
    type: "tool",
    primaryKeyword: "connected papers",
    secondaryKeywords: ["connected papers ai", "research paper graph", "academic ai tool"],
    title: "Connected Papers Review 2026: Features, Pricing & Alternatives",
    description:
      "Connected Papers review 2026: how the research graph tool works, pricing, use cases, pros & cons and alternatives.",
    h1: "Connected Papers Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/connected-papers/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/connected-papers/", "/best/students/"],
    status: "exists",
  },
  {
    id: "A08",
    level: "A",
    slug: "comfyui-video-frame-interpolation",
    path: "/workflows/comfyui-video-frame-interpolation/",
    type: "workflows",
    primaryKeyword: "comfyui video",
    secondaryKeywords: ["comfyui frame interpolation", "comfyui video workflow", "comfyui video upscale"],
    title: "ComfyUI Video Frame Interpolation Workflow 2026 (Step-by-Step)",
    description:
      "ComfyUI video frame interpolation workflow 2026: step-by-step node setup, recommended models, output settings and troubleshooting.",
    h1: "ComfyUI Video Frame Interpolation Workflow 2026",
    cluster: "comfyui-workflows",
    canonical: `${site}/workflows/comfyui-video-frame-interpolation/`,
    schemaType: ["Article", "HowTo"],
    internalLinks: ["/workflows/comfyui-lora-training/", "/tool/comfyui/", "/blog/comfyui-vs-automatic1111-2026/"],
    status: "missing",
  },
  {
    id: "A09",
    level: "A",
    slug: "n8n-rss-to-blog-post",
    path: "/workflows/n8n-rss-to-blog-post/",
    type: "workflows",
    primaryKeyword: "n8n rss automation",
    secondaryKeywords: ["n8n rss to blog", "n8n automation workflow", "rss to wordpress n8n"],
    title: "N8N RSS to Blog Post Workflow 2026 (Step-by-Step)",
    description:
      "Automate RSS to blog post publishing with n8n in 2026: step-by-step workflow, nodes, AI content step and scheduling.",
    h1: "N8N RSS to Blog Post Workflow 2026",
    cluster: "workflow-automation",
    canonical: `${site}/workflows/n8n-rss-to-blog-post/`,
    schemaType: ["Article", "HowTo"],
    internalLinks: ["/tool/n8n/", "/workflows/comfyui-lora-training/"],
    status: "exists",
  },
  {
    id: "A10",
    level: "A",
    slug: "comfyui-lora-training",
    path: "/workflows/comfyui-lora-training/",
    type: "workflows",
    primaryKeyword: "comfyui lora",
    secondaryKeywords: ["comfyui lora training", "train lora comfyui", "comfyui lora workflow"],
    title: "ComfyUI LoRA Training Workflow 2026 (Step-by-Step)",
    description:
      "Train a LoRA in ComfyUI in 2026: step-by-step workflow, dataset prep, training nodes, and tips for better results.",
    h1: "ComfyUI LoRA Training Workflow 2026",
    cluster: "comfyui-workflows",
    canonical: `${site}/workflows/comfyui-lora-training/`,
    schemaType: ["Article", "HowTo"],
    internalLinks: ["/workflows/comfyui-video-frame-interpolation/", "/tool/comfyui/"],
    status: "missing",
  },
  {
    id: "A11",
    level: "A",
    slug: "maxai",
    path: "/alternatives/maxai/",
    type: "alternatives",
    primaryKeyword: "maxai alternatives",
    secondaryKeywords: ["maxai vs", "max ai extension alternatives", "best maxai alternatives"],
    title: "Best MaxAI Alternatives in 2026 (Tested)",
    description:
      "Best MaxAI alternatives in 2026: tested browser AI assistant alternatives with pricing, features and who each is for.",
    h1: "Best MaxAI Alternatives in 2026",
    cluster: "ai-tools",
    canonical: `${site}/alternatives/maxai/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/tool/maxai/", "/alternatives/scenarios-ai/"],
    status: "missing",
  },
  {
    id: "A12",
    level: "A",
    slug: "n8n-vs-make",
    path: "/vs/n8n-vs-make/",
    type: "vs",
    primaryKeyword: "n8n vs make",
    secondaryKeywords: ["n8n vs make.com", "make vs n8n", "workflow automation comparison"],
    title: "N8N vs Make in 2026: Which Automation Tool Wins?",
    description:
      "N8N vs Make in 2026: pricing, features, AI integrations, ease of use and real tests — which workflow automation tool is right for you?",
    h1: "N8N vs Make in 2026",
    cluster: "workflow-automation",
    canonical: `${site}/vs/n8n-vs-make/`,
    schemaType: ["Article", "FAQPage"],
    internalLinks: ["/tool/n8n/", "/tool/make-com/", "/workflows/n8n-rss-to-blog-post/"],
    status: "missing",
  },
  {
    id: "A13",
    level: "A",
    slug: "meetily-review-best-local-ai-meeting-assistant-2026",
    path: "/blog/meetily-review-best-local-ai-meeting-assistant-2026/",
    type: "blog",
    primaryKeyword: "meetily",
    secondaryKeywords: ["meetily review", "local ai meeting assistant", "meetily alternative"],
    title: "Meetily Review 2026: Best Local AI Meeting Assistant?",
    description:
      "Meetily review 2026: the local AI meeting assistant tested — transcription, summaries, privacy and how it compares to cloud tools.",
    h1: "Meetily Review 2026",
    cluster: "ai-reviews",
    canonical: `${site}/blog/meetily-review-best-local-ai-meeting-assistant-2026/`,
    schemaType: ["Article", "FAQPage"],
    internalLinks: ["/best/productivity/", "/blog/agnes-ai-review-free-omni-modal-api-2026/"],
    status: "missing",
  },
  {
    id: "A14",
    level: "A",
    slug: "how-to-write-prompts-for-midjourney-2026",
    path: "/blog/how-to-write-prompts-for-midjourney-2026/",
    type: "blog",
    primaryKeyword: "midjourney prompts",
    secondaryKeywords: ["how to write midjourney prompts", "midjourney prompt guide", "midjourney prompt tips"],
    title: "How to Write Prompts for Midjourney in 2026 (Guide + Examples)",
    description:
      "How to write prompts for Midjourney in 2026: structure, parameters, style modifiers and real examples that work.",
    h1: "How to Write Prompts for Midjourney in 2026",
    cluster: "ai-tutorials",
    canonical: `${site}/blog/how-to-write-prompts-for-midjourney-2026/`,
    schemaType: ["Article", "HowTo", "FAQPage"],
    internalLinks: ["/tool/midjourney/", "/prompts/midjourney-book-cover/", "/blog/best-ai-image-generators-compared-2026/"],
    status: "exists",
  },
  {
    id: "A15",
    level: "A",
    slug: "assembly-ai",
    path: "/tool/assembly-ai/",
    type: "tool",
    primaryKeyword: "assemblyai",
    secondaryKeywords: ["assembly ai review", "assembly ai speech to text", "assembly ai pricing"],
    title: "AssemblyAI Review 2026: Features, Pricing & Real-World Testing",
    description:
      "AssemblyAI review 2026: speech-to-text API features, pricing, accuracy tests, pros & cons and alternatives.",
    h1: "AssemblyAI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/assembly-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/assembly-ai/", "/best/audio/"],
    status: "exists",
  },

  // ================= B 级（20~50 名，主题权威） =================
  {
    id: "B01",
    level: "B",
    slug: "codemod-ai",
    path: "/tool/codemod-ai/",
    type: "tool",
    primaryKeyword: "codemod",
    secondaryKeywords: ["codemod ai", "codemod review", "ai codemod"],
    title: "Codemod AI Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Codemod AI review 2026: AI code transformation features, pricing, real tests, pros & cons and alternatives.",
    h1: "Codemod AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/codemod-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/codemod-ai/", "/best/code/"],
    status: "exists",
  },
  {
    id: "B02",
    level: "B",
    slug: "height-ai",
    path: "/tool/height-ai/",
    type: "tool",
    primaryKeyword: "height ai",
    secondaryKeywords: ["height ai alternatives", "height ai pricing"],
    title: "Height AI Review 2026: AI Project Management Features & Pricing",
    description:
      "Height AI review 2026: AI project management features, pricing, real-world testing, pros & cons, alternatives and FAQ.",
    h1: "Height AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/height-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/height-ai/", "/best/productivity/"],
    status: "exists",
  },
  {
    id: "B03",
    level: "B",
    slug: "ai-for-architects",
    path: "/best/ai-for-architects/",
    type: "best",
    primaryKeyword: "best ai tools for architects",
    secondaryKeywords: ["ai for architects", "ai architecture design tools", "architect ai software"],
    title: "Best AI Tools for Architects in 2026 (Tested)",
    description:
      "Best AI tools for architects in 2026: concept design, BIM, visualization, rendering and documentation — tested and compared.",
    h1: "Best AI Tools for Architects in 2026",
    cluster: "ai-engineering",
    canonical: `${site}/best/ai-for-architects/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/solutions/ai-for-architecture/", "/solutions/ai-for-bim/"],
    status: "exists",
  },
  {
    id: "B04",
    level: "B",
    slug: "ai-for-electrical-engineers",
    path: "/solutions/ai-for-electrical-engineers/",
    type: "solutions",
    primaryKeyword: "ai electrical engineering",
    secondaryKeywords: ["ai for electrical engineers", "electrical engineering ai tools", "ai power systems"],
    title: "AI for Electrical Engineers in 2026: Tools & Workflows",
    description:
      "AI for electrical engineers in 2026: design, power systems, schematics, documentation and the best AI tool stack.",
    h1: "AI for Electrical Engineers in 2026",
    cluster: "ai-engineering",
    canonical: `${site}/solutions/ai-for-electrical-engineers/`,
    schemaType: ["Article", "BreadcrumbList", "ItemList", "FAQPage"],
    internalLinks: ["/solutions/ai-for-bim/", "/solutions/ai-for-structural-engineers/"],
    status: "missing",
  },
  {
    id: "B05",
    level: "B",
    slug: "gen-2-ai",
    path: "/tool/gen-2-ai/",
    type: "tool",
    primaryKeyword: "runway gen-2",
    secondaryKeywords: ["gen 2 ai", "runway gen 2 review", "text to video gen 2"],
    title: "Runway Gen-2 Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Runway Gen-2 review 2026: text/video-to-video features, pricing, real tests, pros & cons and alternatives.",
    h1: "Runway Gen-2 Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/gen-2-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/gen-2-ai/", "/blog/best-ai-video-generators-2026/"],
    status: "exists",
  },
  {
    id: "B06",
    level: "B",
    slug: "zotero-ai",
    path: "/tool/zotero-ai/",
    type: "tool",
    primaryKeyword: "zotero ai",
    secondaryKeywords: ["zotero ai review", "zotero ai features", "zotero research assistant"],
    title: "Zotero AI Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Zotero AI review 2026: research assistant features, pricing, real tests, pros & cons and alternatives.",
    h1: "Zotero AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/zotero-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/zotero-ai/", "/tool/connected-papers/"],
    status: "exists",
  },
  {
    id: "B07",
    level: "B",
    slug: "cursor-dark-mode",
    path: "/prompts/cursor-dark-mode/",
    type: "prompts",
    primaryKeyword: "cursor dark mode",
    secondaryKeywords: ["cursor dark mode prompt", "cursor theme", "cursor editor dark theme"],
    title: "Cursor Dark Mode Prompt 2026 (Step-by-Step)",
    description:
      "Cursor dark mode prompt 2026: current UI steps, theme configuration and version notes for the AI code editor.",
    h1: "Cursor Dark Mode Prompt 2026",
    cluster: "ai-prompts",
    canonical: `${site}/prompts/cursor-dark-mode/`,
    schemaType: ["Article", "HowTo"],
    internalLinks: ["/tool/cursor/", "/prompts/"],
    status: "missing",
  },
  {
    id: "B08",
    level: "B",
    slug: "contentbot",
    path: "/tool/contentbot/",
    type: "tool",
    primaryKeyword: "contentbot",
    secondaryKeywords: ["contentbot ai", "contentbot review", "contentbot pricing"],
    title: "ContentBot Review 2026: Features, Pricing & Real-World Testing",
    description:
      "ContentBot review 2026: AI content writing features, pricing, real output tests, pros & cons and alternatives.",
    h1: "ContentBot Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/contentbot/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/contentbot/", "/best/content-writing/"],
    status: "exists",
  },
  {
    id: "B09",
    level: "B",
    slug: "copysmith",
    path: "/tool/copysmith/",
    type: "tool",
    primaryKeyword: "copysmith",
    secondaryKeywords: ["copysmith ai", "copysmith review", "copysmith pricing"],
    title: "Copysmith Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Copysmith review 2026: AI copywriting features, pricing, real tests, pros & cons and alternatives.",
    h1: "Copysmith Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/copysmith/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/copysmith/", "/best/content-writing/"],
    status: "exists",
  },
  {
    id: "B10",
    level: "B",
    slug: "apple-speechanalyzer-vs-whisper-2026",
    path: "/blog/apple-speechanalyzer-vs-whisper-2026/",
    type: "blog",
    primaryKeyword: "apple speechanalyzer vs whisper",
    secondaryKeywords: ["apple speechanalyzer", "whisper vs apple", "speech to text comparison"],
    title: "Apple SpeechAnalyzer vs Whisper 2026: Which Wins?",
    description:
      "Apple SpeechAnalyzer vs OpenAI Whisper in 2026: accuracy, speed, on-device privacy, pricing and real tests.",
    h1: "Apple SpeechAnalyzer vs Whisper 2026",
    cluster: "ai-reviews",
    canonical: `${site}/blog/apple-speechanalyzer-vs-whisper-2026/`,
    schemaType: ["Article", "FAQPage"],
    internalLinks: ["/tool/whisper/", "/best/audio/"],
    status: "missing",
  },
  {
    id: "B11",
    level: "B",
    slug: "agnes-ai",
    path: "/tool/agnes-ai/",
    type: "tool",
    primaryKeyword: "agnes ai",
    secondaryKeywords: ["agnes ai tool", "agnes ai features", "agnes ai pricing"],
    title: "Agnes AI Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Agnes AI review 2026: features, pricing, real-world testing, pros & cons, alternatives and FAQ.",
    h1: "Agnes AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/agnes-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/blog/agnes-ai-review-free-omni-modal-api-2026/", "/alternatives/agnes-ai/"],
    status: "exists",
  },
  {
    id: "B12",
    level: "B",
    slug: "scenarios-ai",
    path: "/alternatives/scenarios-ai/",
    type: "alternatives",
    primaryKeyword: "scenario ai alternatives",
    secondaryKeywords: ["scenario ai", "scenario alternative", "best scenario ai alternatives"],
    title: "Best Scenario AI Alternatives in 2026 (Tested)",
    description:
      "Best Scenario AI alternatives in 2026: tested game asset generation alternatives with pricing and features.",
    h1: "Best Scenario AI Alternatives in 2026",
    cluster: "ai-tools",
    canonical: `${site}/alternatives/scenarios-ai/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/tool/scenario-ai/", "/alternatives/maxai/"],
    status: "missing",
  },
  {
    id: "B13",
    level: "B",
    slug: "best-ai-tools-for-designers-2026",
    path: "/blog/best-ai-tools-for-designers-2026/",
    type: "blog",
    primaryKeyword: "best ai tools for designers",
    secondaryKeywords: ["ai design tools", "ai for graphic designers", "design ai tools 2026"],
    title: "Best AI Tools for Designers in 2026 (Tested)",
    description:
      "Best AI tools for designers in 2026: image generation, UI design, vector, color and workflow tools tested and compared.",
    h1: "Best AI Tools for Designers in 2026",
    cluster: "ai-design",
    canonical: `${site}/blog/best-ai-tools-for-designers-2026/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/best/designers/", "/blog/best-ai-image-generators-compared-2026/"],
    status: "exists",
  },
  {
    id: "B14",
    level: "B",
    slug: "comfyui-vs-automatic1111-2026",
    path: "/blog/comfyui-vs-automatic1111-2026/",
    type: "blog",
    primaryKeyword: "comfyui vs automatic1111",
    secondaryKeywords: ["comfyui vs a1111", "stable diffusion ui comparison", "comfyui review"],
    title: "ComfyUI vs Automatic1111 in 2026: Which Stable Diffusion UI?",
    description:
      "ComfyUI vs Automatic1111 in 2026: workflows, speed, control, learning curve and real tests — which Stable Diffusion UI wins?",
    h1: "ComfyUI vs Automatic1111 in 2026",
    cluster: "comfyui-workflows",
    canonical: `${site}/blog/comfyui-vs-automatic1111-2026/`,
    schemaType: ["Article", "FAQPage"],
    internalLinks: ["/tool/comfyui/", "/workflows/comfyui-lora-training/", "/workflows/comfyui-video-frame-interpolation/"],
    status: "exists",
  },
  {
    id: "B15",
    level: "B",
    slug: "harpa-ai",
    path: "/tool/harpa-ai/",
    type: "tool",
    primaryKeyword: "harpa ai",
    secondaryKeywords: ["harpa ai review", "harpa chrome extension", "harpa ai pricing"],
    title: "Harpa AI Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Harpa AI review 2026: browser AI assistant features, pricing, real tests, pros & cons and alternatives.",
    h1: "Harpa AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/harpa-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/harpa-ai/", "/alternatives/maxai/"],
    status: "exists",
  },

  // ================= C 级（50~100 名，先判意图） =================
  {
    id: "C01",
    level: "C",
    slug: "vercel-sdk",
    path: "/alternatives/vercel-sdk/",
    type: "alternatives",
    primaryKeyword: "vercel sdk alternatives",
    secondaryKeywords: ["vercel ai sdk alternatives", "vercel sdk vs", "ai sdk comparison"],
    title: "Best Vercel AI SDK Alternatives in 2026 (Tested)",
    description:
      "Best Vercel AI SDK alternatives in 2026: tested LLM SDK options with pricing, features and who each is for.",
    h1: "Best Vercel AI SDK Alternatives in 2026",
    cluster: "ai-engineering",
    canonical: `${site}/alternatives/vercel-sdk/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/blog/how-to-build-an-ai-agent-2026/", "/best/code/"],
    status: "missing",
  },
  {
    id: "C02",
    level: "C",
    slug: "perplexity",
    path: "/tool/perplexity/",
    type: "tool",
    primaryKeyword: "perplexity",
    secondaryKeywords: ["perplexity ai", "perplexity review", "perplexity pricing"],
    title: "Perplexity Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Perplexity review 2026: AI search features, pricing, real tests, pros & cons and alternatives.",
    h1: "Perplexity Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/perplexity/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/perplexity/", "/blog/best-ai-tools-for-research-2026/"],
    status: "exists",
  },
  {
    id: "C03",
    level: "C",
    slug: "midjourney-book-cover",
    path: "/prompts/midjourney-book-cover/",
    type: "prompts",
    primaryKeyword: "midjourney book cover",
    secondaryKeywords: ["midjourney book cover prompt", "ai book cover design", "book cover midjourney"],
    title: "Midjourney Book Cover Prompt 2026 (Ready-to-Use)",
    description:
      "Ready-to-use Midjourney book cover prompt 2026: parameters, style ideas and examples for professional book covers.",
    h1: "Midjourney Book Cover Prompt 2026",
    cluster: "ai-prompts",
    canonical: `${site}/prompts/midjourney-book-cover/`,
    schemaType: ["Article", "HowTo"],
    internalLinks: ["/blog/how-to-write-prompts-for-midjourney-2026/", "/tool/midjourney/"],
    status: "missing",
  },
  {
    id: "C04",
    level: "C",
    slug: "hotpot-ai",
    path: "/tool/hotpot-ai/",
    type: "tool",
    primaryKeyword: "hotpot ai",
    secondaryKeywords: ["hotpot ai review", "hotpot image generator", "hotpot ai pricing"],
    title: "Hotpot AI Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Hotpot AI review 2026: image generation and editing features, pricing, real tests, pros & cons and alternatives.",
    h1: "Hotpot AI Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/hotpot-ai/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/hotpot-ai/", "/blog/best-ai-image-generators-compared-2026/"],
    status: "exists",
  },
  {
    id: "C05",
    level: "C",
    slug: "veracode",
    path: "/tool/veracode/",
    type: "tool",
    primaryKeyword: "veracode",
    secondaryKeywords: ["veracode ai", "veracode review", "application security ai"],
    title: "Veracode Review 2026: Features, Pricing & Real-World Testing",
    description:
      "Veracode review 2026: application security features, AI capabilities, pricing, pros & cons and alternatives.",
    h1: "Veracode Review 2026",
    cluster: "ai-tools",
    canonical: `${site}/tool/veracode/`,
    schemaType: ["SoftwareApplication", "FAQPage"],
    internalLinks: ["/tools/veracode/", "/best/code/"],
    status: "exists",
  },
  {
    id: "C06",
    level: "C",
    slug: "pitch-deck",
    path: "/templates/pitch-deck/",
    type: "templates",
    primaryKeyword: "pitch deck template",
    secondaryKeywords: ["startup pitch deck template", "pitch deck template 2026", "investor deck template"],
    title: "Pitch Deck Template 2026: Free Startup Deck (10 Slides)",
    description:
      "Free startup pitch deck template 2026: 10-slide investor deck structure, examples, tips and a copy-ready format.",
    h1: "Pitch Deck Template 2026",
    cluster: "business-templates",
    canonical: `${site}/templates/pitch-deck/`,
    schemaType: ["Article", "HowTo"],
    internalLinks: ["/templates/qbr-template/", "/templates/prd-template/"],
    status: "missing",
  },
  {
    id: "C07",
    level: "C",
    slug: "best-ai-tools-for-small-business-2026",
    path: "/blog/best-ai-tools-for-small-business-2026/",
    type: "blog",
    primaryKeyword: "best ai tools for small business",
    secondaryKeywords: ["ai for small business", "small business ai tools", "cheap ai tools business"],
    title: "Best AI Tools for Small Business in 2026 (Tested)",
    description:
      "Best AI tools for small business in 2026: tested budget-friendly tools for marketing, finance, support and operations.",
    h1: "Best AI Tools for Small Business in 2026",
    cluster: "ai-business",
    canonical: `${site}/blog/best-ai-tools-for-small-business-2026/`,
    schemaType: ["Article", "ItemList", "FAQPage"],
    internalLinks: ["/best/small-business/", "/blog/best-ai-tools-for-content-writers-2026/"],
    status: "exists",
  },
  {
    id: "C08",
    level: "C",
    slug: "how-to-use-ai-for-sales-2026",
    path: "/blog/how-to-use-ai-for-sales-2026/",
    type: "blog",
    primaryKeyword: "how to use ai for sales",
    secondaryKeywords: ["ai sales tools", "ai for sales teams", "sales ai workflow"],
    title: "How to Use AI for Sales in 2026 (Step-by-Step)",
    description:
      "How to use AI for sales in 2026: lead generation, outreach, CRM automation, forecasting and real workflow examples.",
    h1: "How to Use AI for Sales in 2026",
    cluster: "ai-business",
    canonical: `${site}/blog/how-to-use-ai-for-sales-2026/`,
    schemaType: ["Article", "HowTo", "FAQPage"],
    internalLinks: ["/best/ai-for-sales-teams/", "/best/productivity/"],
    status: "exists",
  },
  {
    id: "C09",
    level: "C",
    slug: "ai-for-structural-engineers",
    path: "/solutions/ai-for-structural-engineers/",
    type: "solutions",
    primaryKeyword: "ai for structural engineers",
    secondaryKeywords: ["structural engineering ai tools", "ai structural analysis", "ai for structural design"],
    title: "AI for Structural Engineers in 2026: Tools & Workflows",
    description:
      "AI for structural engineers in 2026: analysis, design, drawing review, documentation and the best AI tool stack.",
    h1: "AI for Structural Engineers in 2026",
    cluster: "ai-engineering",
    canonical: `${site}/solutions/ai-for-structural-engineers/`,
    schemaType: ["Article", "BreadcrumbList", "ItemList", "FAQPage"],
    internalLinks: ["/solutions/ai-for-bim/", "/solutions/ai-for-electrical-engineers/", "/solutions/ai-for-architecture/"],
    status: "missing",
  },
  {
    id: "C10",
    level: "C",
    slug: "elevenlabs-vs-chatgpt",
    path: "/vs/elevenlabs-vs-chatgpt/",
    type: "vs",
    primaryKeyword: "elevenlabs vs chatgpt",
    secondaryKeywords: ["elevenlabs vs chatgpt voice", "chatgpt voice vs elevenlabs", "ai voice comparison"],
    title: "ElevenLabs vs ChatGPT Voice in 2026: Which Wins?",
    description:
      "ElevenLabs vs ChatGPT voice in 2026: quality, pricing, features and real tests — which AI voice tool is right for you?",
    h1: "ElevenLabs vs ChatGPT Voice in 2026",
    cluster: "ai-audio",
    canonical: `${site}/vs/elevenlabs-vs-chatgpt/`,
    schemaType: ["Article", "FAQPage"],
    internalLinks: ["/tool/elevenlabs/", "/tool/chatgpt/", "/blog/how-to-use-elevenlabs-for-podcasts-2026/"],
    status: "missing",
  },
];

// 唯一 URL 检查（任务书 50 页去重后 49 个唯一 URL）
export const seoPageIndex: Record<string, SeoPage> = Object.fromEntries(
  seoPages.map(p => [p.path, p])
);

export function getPageByPath(path: string): SeoPage | undefined {
  return seoPageIndex[path];
}

export function getPagesByLevel(level: PageLevel): SeoPage[] {
  return seoPages.filter(p => p.level === level);
}
